log_level: info
api_key: devkey
api_secret: devsecret
ws_url: ws://livekit:7880
s3:
  access_key: minioadmin
  secret: minioadmin
  region: us-east-1
  endpoint: http://minio:9000
  bucket: recordings
  force_path_style: true
